In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

In [20]:
df = pd.read_csv('./data/car_price_prediction.csv')
df.head()

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

In [21]:
print("Dataset Shape:", df.shape)

df.info()

Dataset Shape: (19237, 18)
<class 'pandas.DataFrame'>
RangeIndex: 19237 entries, 0 to 19236
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                19237 non-null  int64
 1   Price             19237 non-null  int64
 2   Levy              19237 non-null  str
 3   Manufacturer      19237 non-null  str
 4   Model             19237 non-null  str
 5   Prod. year        19237 non-null  int64
 6   Category          19237 non-null  str
 7   Leather interior  19237 non-null  str
 8   Fuel type         19237 non-null  str
 9   Engine volume     19237 non-null  str
 10  Mileage           19237 non-null  str
 11  Cylinders         19237 non-null  float64
 12  Gear box type     19237 non-null  str
 13  Drive wheels      19237 non-null  str
 14  Doors             19237 non-null  str
 15  Wheel             19237 non-null  str
 16  Color             19237 non-null  str
 17  Airbags           19237 non-null  int64
dtypes: float64(1), int64(4), str(13)
memory usage: 4.0 MB

In [39]:
pd.DataFrame(df.Price.describe(include="all").T)

              Price
count  1.892400e+04
mean   1.858744e+04
std    1.921356e+05
min    1.000000e+00
25%    5.331000e+03
50%    1.317200e+04
75%    2.206300e+04
max    2.630750e+07

In [23]:
print("Duplicates:", df.duplicated().sum())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nUnique Values:")
print(df.nunique())

Duplicates: 313

Missing Values:
ID                  0
Price               0
Levy                0
Manufacturer        0
Model               0
Prod. year          0
Category            0
Leather interior    0
Fuel type           0
Engine volume       0
Mileage             0
Cylinders           0
Gear box type       0
Drive wheels        0
Doors               0
Wheel               0
Color               0
Airbags             0
dtype: int64

Unique Values:
ID                  18924
Price                2315
Levy                  559
Manufacturer           65
Model                1590
Prod. year             54
Category               11
Leather interior        2
Fuel type               7
Engine volume         107
Mileage              7687
Cylinders              13
Gear box type           4
Drive wheels            3
Doors                   3
Wheel                   2
Color                  16
Airbags                17
dtype: int64

In [24]:
df = df.drop_duplicates()

In [25]:
# unique = df.nunique()
# pd.DataFrame(
#     {
#         "unique": unique
#     }
# ).T

In [26]:
# df=df.drop(['ID','Doors'],axis=1)
# num_cols= ['Prod. year','Engine volume','Mileage','Cylinders','Levy']
# cat_cols= ['Manufacturer', 'Model', 'Category', 'Leather interior',
#            'Fuel type', 'Gear box type', 'Drive wheels', 'Wheel',
#            'Color', 'Airbags']
# for col in df.columns:
#     if col not in num_col:
#         cat_col.append(col)
        
# print(cat_col)

In [27]:
# for col in cat_cols:
#     print("column name : " , col)
#     print(pd.DataFrame(df[col].unique()))
#     # print(df[col].value_counts())
#     print('*'*50)

In [28]:

# df['Levy'] = df['Levy'].replace('-',0)
# df['Mileage'] = df['Mileage'].str.replace('km' , '')
# df['Engine volume'] = df['Engine volume'].str.replace(' Turbo' , '')

In [29]:
# for col in num_col:
#     print("column name : " , col)
#     # print(pd.DataFrame(df[col].unique()))
#     print(df[col].value_counts())
#     print('*'*50)

In [30]:
# df['Engine volume'].unique()

In [31]:
# df[num_cols] = df[num_cols].astype('float64')
# df[cat_cols] = df[cat_cols].astype('category')

In [32]:
# X = df.drop('Price',axis=1)
# y = df['Price']

In [33]:
# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=42
# )

In [34]:
# scaler = MinMaxScaler()

# X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
# X_test[num_cols] = scaler.transform(X_test[num_cols])

In [35]:
# from sklearn.preprocessing import OneHotEncoder

# encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
# encoder.set_output(transform="pandas")


# X_train_encoded = encoder.fit_transform(X_train[cat_cols])
# X_test_encoded = encoder.transform(X_test[cat_cols])


# X_train = pd.concat([X_train.drop(columns=cat_cols), X_train_encoded], axis=1)
# X_test = pd.concat([X_test.drop(columns=cat_cols), X_test_encoded], axis=1)

## model_1

In [36]:
# import numpy as np
# import pandas as pd
# from sklearn.model_selection import train_test_split, GridSearchCV
# from sklearn.preprocessing import StandardScaler
# from sklearn.pipeline import Pipeline
# from sklearn.linear_model import Ridge
# from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
# from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
# from xgboost import XGBRegressor
# import joblib

# models = {
#     "Ridge": (
#         Pipeline([("scaler", StandardScaler()), ("model", Ridge())]),
#         {"model__alpha": [0.01, 0.1, 1, 10, 100]},
#     ),
#     "RandomForest": (
#         RandomForestRegressor(random_state=42, n_jobs=-1),
#         {
#             "n_estimators": [100, 200],
#             "max_depth": [None, 10, 20],
#             "min_samples_split": [2, 5],
#         },
#     ),
#     "GradientBoosting": (
#         GradientBoostingRegressor(random_state=42),
#         {
#             "n_estimators": [100, 200],
#             "learning_rate": [0.05, 0.1],
#             "max_depth": [3, 5],
#         },
#     ),
#     "XGBoost": (
#         XGBRegressor(random_state=42, n_jobs=-1),
#         {
#             "n_estimators": [100, 300],
#             "learning_rate": [0.05, 0.1],
#             "max_depth": [3, 6],
#             "subsample": [0.8, 1.0],
#         },
#     ),
# }


# results = []
# best_models = {}

# for name, (estimator, params) in models.items():
#     print(f"Training {name}...")
#     grid = GridSearchCV(
#         estimator,
#         param_grid=params,
#         cv=5,
#         scoring="neg_root_mean_squared_error",
#         n_jobs=-1,
#     )
#     grid.fit(X_train, y_train)

#     best = grid.best_estimator_
#     best_models[name] = best
#     pred = best.predict(X_test)

#     results.append({
#         "Model": name,
#         "Best Params": grid.best_params_,
#         "CV RMSE": -grid.best_score_,
#         "Test RMSE": np.sqrt(mean_squared_error(y_test, pred)),
#         "Test MAE": mean_absolute_error(y_test, pred),
#         "Test R2": r2_score(y_test, pred),
#     })


# results_df = pd.DataFrame(results).sort_values("CV RMSE")
# print(results_df.drop(columns="Best Params").to_string(index=False))

# best_name = results_df.iloc[0]["Model"]
# best_model = best_models[best_name]  

# print(f"\nBest model: {best_name}")
# print(results_df.iloc[0]["Best Params"])


# joblib.dump(best_model, "best_model.pkl")
# print(f"Saved: {best_name} -> best_model.pkl")